export const CHECKLIST_ITEMS = [
  { id: 1,  category: 'NCCP',                 description: 'Credit Guide signed and dated prior to CCR pull',                        cls: 'major' },
  { id: 2,  category: 'NCCP',                 description: 'Needs Analysis complete and on file',                                     cls: 'major' },
  { id: 3,  category: 'NCCP',                 description: 'Preliminary Assessment complete and on file',                             cls: 'major' },
  { id: 4,  category: 'NCCP',                 description: 'CPD signed by client',                                                    cls: 'major' },
  { id: 5,  category: 'NCCP',                 description: 'R&O matches final product / BID Notes',                                   cls: 'major' },
  { id: 6,  category: 'NCCP',                 description: 'BID Notes sufficient — full justification documented',                    cls: 'major' },
  { id: 7,  category: 'NCCP',                 description: 'CCR attached to file',                                                    cls: 'minor' },
  { id: 8,  category: 'ID',                   description: 'Name matches application across all documents',                           cls: 'minor' },
  { id: 9,  category: 'ID',                   description: 'DOB matches application',                                                 cls: 'minor' },
  { id: 10, category: 'ID',                   description: 'Address matches application',                                             cls: 'minor' },
  { id: 11, category: 'ID',                   description: 'ID not expired',                                                          cls: 'minor' },
  { id: 12, category: 'ID',                   description: 'Medicare card on file — name, expiry, dependents checked',               cls: 'minor' },
  { id: 13, category: 'ID',                   description: 'Dependents recorded in Mercury / AOL / Servicing Calc',                  cls: 'major_servicing' },
  { id: 14, category: 'Income',               description: 'PAYG — payslip name, employer, salary YTD verified',                     cls: 'major_servicing' },
  { id: 15, category: 'Income',               description: 'PAYG — income annualised incorrectly + impacts serviceability',          cls: 'major_servicing' },
  { id: 16, category: 'Income',               description: 'PAYG — OT/Allowances calculated and noted if applicable',               cls: 'major_servicing' },
  { id: 17, category: 'Income',               description: 'PAYG — HECS/HELP checked and captured if applicable',                   cls: 'major_servicing' },
  { id: 18, category: 'Income',               description: 'S/E — NOA and ITR figures match exactly',                                cls: 'major_servicing' },
  { id: 19, category: 'Income',               description: 'S/E — Financials/CTR name, NPBT, depreciation verified',                cls: 'major_servicing' },
  { id: 20, category: 'Income',               description: 'S/E — Depreciation schedule present',                                    cls: 'major_servicing' },
  { id: 21, category: 'Income',               description: 'S/E — Hire purchase liabilities checked in financials',                  cls: 'major_servicing' },
  { id: 22, category: 'Income',               description: 'S/E — IAWO correctly identified and included separately',                cls: 'major_servicing' },
  { id: 23, category: 'Income',               description: 'Government income input correctly in CRM and AOL',                       cls: 'major_servicing' },
  { id: 24, category: 'Income',               description: 'Rental income — tenancy agreement / COS reviewed',                      cls: 'major_servicing' },
  { id: 25, category: 'Income',               description: 'Salary credits / bank statements support declared income',               cls: 'major_servicing' },
  { id: 26, category: 'Income',               description: 'TFN not redacted',                                                       cls: 'major' },
  { id: 27, category: 'HEM / Living Expenses', description: 'HEM benchmarks applied correctly for lender',                           cls: 'major_servicing' },
  { id: 28, category: 'HEM / Living Expenses', description: 'Childcare declared correctly per age/Centrelink',                       cls: 'major_servicing' },
  { id: 29, category: 'HEM / Living Expenses', description: 'School fees declared — dependents aged 5–17',                          cls: 'major_servicing' },
  { id: 30, category: 'HEM / Living Expenses', description: 'Private health insurance calculated and declared',                      cls: 'major_servicing' },
  { id: 31, category: 'HEM / Living Expenses', description: 'Board/Primary Residence Cost — correct lender figure applied',         cls: 'major_servicing' },
  { id: 32, category: 'HEM / Living Expenses', description: 'LE figures match across AOL and Servicing Calc',                       cls: 'major' },
  { id: 33, category: 'HEM / Living Expenses', description: 'Transaction statements on file to support LE',                         cls: 'minor' },
  { id: 34, category: 'Liabilities',          description: 'All liabilities match CCR',                                              cls: 'major_servicing' },
  { id: 35, category: 'Liabilities',          description: 'Statements on file for each liability',                                  cls: 'minor' },
  { id: 36, category: 'Liabilities',          description: 'Conduct reviewed — no undisclosed issues',                              cls: 'major_servicing' },
  { id: 37, category: 'Liabilities',          description: 'Liability ownership correct',                                            cls: 'major_servicing' },
  { id: 38, category: 'Liabilities',          description: 'Hire purchase noted and added correctly',                               cls: 'minor' },
  { id: 39, category: 'Assets',               description: 'Assets declared — savings, motor vehicle, home contents',               cls: 'minor' },
  { id: 40, category: 'Assets',               description: 'Assets declared — super',                                               cls: 'minor' },
  { id: 41, category: 'Assets',               description: 'Assets match across CRM, AOL and Servicing Calc',                       cls: 'minor' },
  { id: 42, category: 'Servicing Calc',       description: 'Income correctly input in Servicing Calc',                               cls: 'major_servicing' },
  { id: 43, category: 'Servicing Calc',       description: 'All liabilities included in Servicing Calc',                            cls: 'major_servicing' },
  { id: 44, category: 'Servicing Calc',       description: 'Pass/Fail result noted on file',                                        cls: 'major_servicing' },
  { id: 45, category: 'Product / BID',        description: 'Correct product selected',                                               cls: 'major' },
  { id: 46, category: 'Product / BID',        description: 'Interest rate discount correctly applied',                               cls: 'major' },
  { id: 47, category: 'Product / BID',        description: 'Loan features from R&O included',                                       cls: 'minor' },
  { id: 48, category: 'Product / BID',        description: 'I/O correctly flagged if applicable',                                   cls: 'minor' },
  { id: 49, category: 'Product / BID',        description: 'Exit strategy documented if loan term extends past age 65',             cls: 'major' },
  { id: 50, category: 'Submission Quality',   description: 'Email trail on file — all correspondence evidenced',                    cls: 'major' },
  { id: 51, category: 'Submission Quality',   description: 'Supporting documents attached in OneDrive / CRM',                      cls: 'major' },
  { id: 52, category: 'Submission Quality',   description: 'Notes in CRM are clear, consistent and complete',                      cls: 'major' },
  { id: 53, category: 'Submission Quality',   description: 'No conflicting information across systems',                             cls: 'major' },
  { id: 54, category: 'Submission Quality',   description: 'Security — correct address, ownership, valuation/COS',                 cls: 'major' },
  { id: 55, category: 'Submission Quality',   description: 'Applicant details consistent across all platforms',                     cls: 'major' },
  { id: 56, category: 'File Structure',       description: 'Naming convention',                                                      cls: 'minor' },
  { id: 57, category: 'File Structure',       description: 'All documents PDF',                                                      cls: 'minor' },
];

export const CATEGORIES = [...new Set(CHECKLIST_ITEMS.map(i => i.category))];
